apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  labels:
    app: discord-app
spec:
  selector:
    matchLabels:
      app: discord-bot
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadate:
      labels:
        app: discord-bot
    spec:
      containers:
        name: discord-bot
        image: zackbaum/discord_practice_bot
        imagePullPolicy: Always
        ports:
          containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
          cpu: "500m"